name: Update variables

on:
    workflow_dispatch:

jobs:
    update_variables:
        runs-on: ubuntu-latest
        steps:

            - name: Set default identity
              run: |
                git config --global user.email ${{ vars.USER_EMAIL }}
                git config --global user.name ${{ vars.USER_NAME }}
            
            - name: Checkout repository
              uses: actions/checkout@v4
        
            - name: Create and write to file
              run: |
                # replace each line in constants.cs with the corresponding environment variable
                echo "public const string constant_1 = ${{ vars.CONSTANT_ONE }};" >> constants.cs
                # echo "public const string constant_2 = ${{ vars.CONSTANT_TWO }};" >> constants.cs
                # echo "public const string constant_3 = ${{ vars.CONSTANT_THREE }};" >> constants.cs
                # echo "public const string constant_4 = ${{ vars.CONSTANT_FOUR }};" >> constants.cs
                # echo "public const string constant_5 = ${{ vars.CONSTANT_FIVE }};" >> constants.cs
                # echo "public const string constant_6 = ${{ vars.CONSTANT_SIX }};" >> constants.cs
                # echo "public const string constant_7 = ${{ vars.CONSTANT_SEVEN }};" >> constants.cs
                # echo "public const string constant_8 = ${{ vars.CONSTANT_EIGHT }};" >> constants.cs
                # echo "public const string constant_9 = ${{ vars.CONSTANT_NINE }};" >> constants.cs
                # echo "public const string constant_10 = ${{ vars.CONSTANT_TEN }};" >> constants.cs
                git add constants.cs
                git commit -m "Update constnts.cs file with new entry"
                git push